// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nzmgatwsdhwsspliaxsk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im56bWdhdHdzZGh3c3NwbGlheHNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk5MDMxMjAsImV4cCI6MjA1NTQ3OTEyMH0.52lEnNMwGBZWX9NvIiUJljAajj050UWChcIdt7-bMtg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);